language: elixir
elixir: '1.10'
otp_release: '21.0'

env:
  MIX_ENV: test

services:
  - postgresql

before_script:
  - mix deps.get --only test
  - mix do ecto.create, ecto.migrate

script:
  - mix credo
  - mix test
